### ISSUE TITLE
Issues while migrating Metastore from old databricks workspace to the new one.

### ISSUE THREAD

**Issue by raknaik** [mrchristine/db-migration#11]
Hi Team,

We tried to follow the document steps for migrating the metastore from our existing workspace on to the new databricks workspace.

Initially when we executed the script, it was successful - but we noticed that partial database and table information were migrated from old workspace to the new one.

We tried to re-migrate the second time - but we ended up facing issues while executing the export.py script with below error.

Creating remote Spark Session
post: https://westeurope.azuredatabricks.net/api/1.2/contexts/create
post: https://westeurope.azuredatabricks.net/api/1.2/commands/execute
Get: https://westeurope.azuredatabricks.net/api/1.2/commands/status
Get: https://westeurope.azuredatabricks.net/api/1.2/commands/status
Get: https://westeurope.azuredatabricks.net/api/1.2/commands/status
Get: https://westeurope.azuredatabricks.net/api/1.2/commands/status
Get: https://westeurope.azuredatabricks.net/api/1.2/commands/status
ERROR:
<span class="ansi-red-fg">AttributeError</span>: databaseName
Traceback (most recent call last):
  File "export_db.py", line 132, in <module>
    main()
  File "export_db.py", line 126, in main
    hive_c.export_hive_metastore()
  File "C:\migration-tools\db-migration-master\dbclient\HiveClient.py", line 161, in export_hive_metastore
    all_dbs = self.log_all_databases(cid, ec_id, ms_dir)
  File "C:\migration-tools\db-migration-master\dbclient\HiveClient.py", line 108, in log_all_databases
    num_of_dbs = ast.literal_eval(results['data'])
KeyError: 'data'

C:\Users\dsvm\Desktop\db-migration-master>python export_db.py --metastore --azure --profile tpold
Traceback (most recent call last):
  File "export_db.py", line 135, in <module>
    main()
  File "export_db.py", line 25, in main
    token = login_args['token']
KeyError: 'token'

**Comment by mrchristine** [comment]
It looks like there's 2 stacktraces here. 

1. There is a problem exporting the database and possibly an empty result. I can add a check here for that. Thanks for reporting. 

2. The second attempt shows a credential issue. It can't find the token for the environment. Verify your credentials and try again.

**Comment by mrchristine** [comment]
I think I understand the issue, the cluster uses the latest Spark release which has changed how the `show database` field returns the data properties. I've updated the tool to use the correct property. Please pull the latest changes and try again.

**Comment by raknaik** [comment]
Thanks for the quick action on this issue. I tried to use the latest one and executed the migration task. Script is getting aborted after some time of execution with the below error.

post: https://westeurope.azuredatabricks.net/api/1.2/commands/execute
Get: https://westeurope.azuredatabricks.net/api/1.2/commands/status
Traceback (most recent call last):
  File "export_db.py", line 135, in <module>
    main()
  File "export_db.py", line 129, in main
    hive_c.export_hive_metastore()
  File "C:\Users\dsvm\Desktop\db-migration-master\dbclient\HiveClient.py", line 213, in export_hive_metastore
    total_failed_entries = self.get_num_of_lines(failed_metastore_log_path)
  File "C:\Users\dsvm\Desktop\db-migration-master\dbclient\HiveClient.py", line 191, in get_num_of_lines
    return i + 1
UnboundLocalError: local variable 'i' referenced before assignment

**Comment by raknaik** [comment]
And also after importing it to the new workspace, the sample data table shows its empty. So is there a need to performing any explicit msck repair or table refresh on the new workspace to see the sample data of the table records?

**Comment by mrchristine** [comment]
There was a bug in that function if the failed logfile is empty, in your case it was. I've added a check for that and pushed a commit to fix that. 

This export / import is the metadata only. Your actual data needs to be re-mounted or copied over via another process.

**Comment by raknaik** [comment]
I tried to import the metastore and ended up facing issues with some of the tables DDL import.

Importing table dtc_monitor.vehicle_ecu_faultcode
ERROR:
org.apache.spark.sql.catalyst.parser.ParseException:
{'resultType': 'error', 'summary': 'org.apache.spark.sql.catalyst.parser.ParseException: ', 'cause': '---------------------------------------------------------------------------\nPy4JJavaError                             Traceback (most recent call last)\n/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)\n     97         try:\n---> 98             return f(*a, **kw)\n     99         except py4j.protocol.Py4JJavaError as e:\n\n/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)\n    327                     "An error occurred while calling {0}{1}{2}.\\n".\n--> 328                     format(target_id, ".", name), value)\n    329             else:\n\nPy4JJavaError: An error occurred while calling o204.sql.\n: org.apache.spark.sql.catalyst.parser.ParseException: \nno viable alternative at input \'CREATE TABLE `dtc_monitor`.`vehicle_ecu_faultcode` (\\n  )\'(line 2, pos 2)\n\n== SQL ==\n CREATE TABLE `dtc_monitor`.`vehicle_ecu_faultcode` (\n  )\n--^^^\nUSING delta\nLOCATION \'dbfs:/mnt/Test-databricks/use_cases/tp_reservoir/dev/dtc_monitor/databricks_output/vehicle_ecu_faultcode\' \n\n\tat org.apache.spark.sql.catalyst.parser.ParseException.withCommand(ParseDriver.scala:268)\n\tat org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parse(ParseDriver.scala:135)\n\tat org.apache.spark.sql.execution.SparkSqlParser.parse(SparkSqlParser.scala:55)\n\tat org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parsePlan(ParseDriver.scala:81)\n\tat com.databricks.sql.parser.DatabricksSqlParser.$anonfun$parsePlan$1(DatabricksSqlParser.scala:70)\n\tat com.databricks.sql.parser.DatabricksSqlParser.parse(DatabricksSqlParser.scala:90)\n\tat com.databricks.sql.parser.DatabricksSqlParser.parsePlan(DatabricksSqlParser.scala:67)\n\tat org.apache.spark.sql.SparkSession.$anonfun$sql$2(SparkSession.scala:662)\n\tat org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)\n\tat org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:662)\n\tat org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:829)\n\tat org.apache.spark.sql.SparkSession.sql(SparkSession.scala:659)\n\tat sun.reflect.GeneratedMethodAccessor179.invoke(Unknown Source)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)\n\tat py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)\n\tat py4j.Gateway.invoke(Gateway.java:295)\n\tat py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)\n\tat py4j.commands.CallCommand.execute(CallCommand.java:79)\n\tat py4j.GatewayConnection.run(GatewayConnection.java:251)\n\tat java.lang.Thread.run(Thread.java:748)\n\n\nDuring handling of the above exception, another exception occurred:\n\nParseException                            Traceback (most recent call last)\n<command--1> in <module>\n      2   )\n      3 USING delta\n----> 4 LOCATION \'dbfs:/mnt/Test-databricks/use_cases/tp_reservoir/dev/dtc_monitor/databricks_output/vehicle_ecu_faultcode\' """)\n\n/databricks/spark/python/pyspark/sql/session.py in sql(self, sqlQuery)\n    702         [Row(f1=1, f2=u\'row1\'), Row(f1=2, f2=u\'row2\'), Row(f1=3, f2=u\'row3\')]\n    703         """\n--> 704         return DataFrame(self._jsparkSession.sql(sqlQuery), self._wrapped)\n    705 \n    706     @since(2.0)\n\n/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in __call__(self, *args)\n   1303         answer = self.gateway_client.send_command(command)\n   1304         return_value = get_return_value(\n-> 1305             answer, self.gateway_client, self.target_id, self.name)\n   1306 \n   1307         for temp_arg in temp_args:\n\n/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)\n    100             converted = convert_exception(e.java_exception)\n    101             if not isinstance(converted, UnknownException):\n--> 102                 raise converted\n    103             else:\n    104                 raise\n\nParseException: \nno viable alternative at input \'CREATE TABLE

**Comment by mrchristine** [comment]
I believe this is another Spark 3.0 API changes that is causing the import to fail.
I've reverted back to use the latest DBR 6.x line of runtimes in the code. Please pull the latest and try again.
