### ISSUE TITLE
Add ability to specify the logs destination folder

### ISSUE THREAD

**Issue by saldroubi** [mrchristine/db-migration#28]
Could you add the ability to specify the destination folder instead of always being azure_logs?

**Comment by mrchristine** [comment]
Yes, we can look at making this configurable. 
What's the current challenge of using this default location? What problem are we trying to solve?

**Comment by saldroubi** [comment]
I would like to export multiple workspaces and if I try to do this in parallel then everything would pointing to the same folder hardcoded location.

**Comment by mrchristine** [comment]
@saldroubi added an export directory flag for you to set different directories. I'll close this out now. Re-open if this is still an issue.
