### ISSUE TITLE
Clarification as to what "migration" means for this project

### ISSUE THREAD

**Issue by go-dustin** [mrchristine/db-migration#33]
Due to the cost factor of Databricks, I've been asked to figure out how to migrate off of the platform. I'm unclear what migration means in the context of this project. Is it migration from one Databricks environment to another or is it migration off of the platform?

**Comment by mrchristine** [comment]
This is meant for users who want to migrate between Databricks workspaces, which often means migrating between cloud providers, or to different AWS regions.

**Comment by go-dustin** [comment]
Thanks.. It looks like a very useful project.. I'll mention it to my coworkers at Google..
