### ISSUE TITLE
Export Metadata doesn't work if Metastore work cluster doesn't have access

### ISSUE THREAD

**Issue by neil90-db** [mrchristine/db-migration#4]
How the current code is implemented when exporting data from metastore if the cluster json spec used in the data/ folder does not have a instance profile that has access to the S3 buckets that are defined for the tables it will fail to get the ddl for those tables.

**Comment by mrchristine** [comment]
Overall, we need to read the failed exports, edit the cluster via each IAM roles and try again. 
```

Loop through all IAM roles:
1. Edit cluster
2. Read failed table log
3. Try to get DDL again
4. Log DDL (success or failure)
5. Repeat
```

**Comment by mrchristine** [comment]
Resolved for AWS workspaces to allow iterating through IAM roles to access table data that originally failed.
