### ISSUE TITLE
Import users without notifications?

### ISSUE THREAD

**Issue by subaduba** [mrchristine/db-migration#51]
Hello! Is it possible to import users into a new workspace without notifying the users? Thank you.

**Comment by mrchristine** [comment]
Not possible today. We could consider this if added to the product. Request it here via the Ideas portal: https://docs.databricks.com/resources/ideas.html

**Comment by subaduba** [comment]
Thanks @mrchristine. To provide some background, I have a highly used single tenant deployment right now, and I am looking to migrate to an E2 one. I wanted to start migrating some of the users, metadata, etc...but not have folks use it until I can do some sanity checking. I can just let them know to ignore the alerts for now, but I wanted to check.
